{
 "title": "Diagnosi",
 "time": { "from": "2024-05-31T22:00:00.000Z", "to": "2024-06-11T22:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "deviceId",
    "query": "from(bucket: \"homeassistant\")\n  |> range(start: 0)\n  |> keep(columns: [\"device_id\"])\n  |> group(columns: [\"device_id\"])\n  |> distinct(column: \"device_id\")\n  |> filter(fn: (r) => exists r.device_id)\n  |> map(fn: (r) => ({\n      _value: \"\\\"\" + string(v: r.device_id) + \"\\\"\"\n  }))\n"
   }
  ]
 },
 "panels": [
  { "title": "Tempo Reale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Potenza",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"power\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"current\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tensione",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"voltage\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Fattore di potenza",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"power_factor\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Storico", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Potenza",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"power\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Corrente",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"current\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tensione",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"voltage\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Fattore di potenza",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"power_factor\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Energia",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"device_class\"] == \"energy\" and r[\"type_measure\"] == \"energia\")\n  |> filter(fn: (r) => r[\"device_id\"] == ${deviceId})\n  |> group(columns: [\"device_id\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Profili Giornalieri", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Profilo giorno medio: PRIMAVERA",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\ncalcStagione = (mese) => {\n    return if mese >= 3 and mese <= 5 then \"Primavera\"\n    else if mese >= 6 and mese <= 8 then \"Estate\"\n    else if mese >= 9 and mese <= 11 then \"Autunno\"\n    else \"Inverno\"\n}\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r._field == \"value\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      dayOfWeek: date.weekDay(t: r._time),\n      ora: date.hour(t: r._time),\n      stagione: calcStagione(mese: date.month(t: r._time))\n  }))\n\n  |> filter(fn: (r) => r.stagione == \"Primavera\")\n  |> map(fn: (r) => ({ r with dayOfWeek: if r.dayOfWeek == 0 then 7 else r.dayOfWeek }))\n  |> group(columns: [\"dayOfWeek\", \"ora\"]) \n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\n  |> sort(columns: [\"ora\"])\n  |> group(columns: [\"dayOfWeek\"]) "
    }
   ]
  },
  {
   "title": "Profilo giorno medio: ESTATE",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\ncalcStagione = (mese) => {\n    return if mese >= 3 and mese <= 5 then \"Primavera\"\n    else if mese >= 6 and mese <= 8 then \"Estate\"\n    else if mese >= 9 and mese <= 11 then \"Autunno\"\n    else \"Inverno\"\n}\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r._field == \"value\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      dayOfWeek: date.weekDay(t: r._time),\n      ora: date.hour(t: r._time),\n      stagione: calcStagione(mese: date.month(t: r._time))\n  }))\n\n  |> filter(fn: (r) => r.stagione == \"Estate\")\n  |> map(fn: (r) => ({ r with dayOfWeek: if r.dayOfWeek == 0 then 7 else r.dayOfWeek }))\n  |> group(columns: [\"dayOfWeek\", \"ora\"]) \n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\n  |> sort(columns: [\"ora\"])\n  |> group(columns: [\"dayOfWeek\"]) "
    }
   ]
  },
  {
   "title": "Profilo giorno medio: AUTUNNO",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\ncalcStagione = (mese) => {\n    return if mese >= 3 and mese <= 5 then \"Primavera\"\n    else if mese >= 6 and mese <= 8 then \"Estate\"\n    else if mese >= 9 and mese <= 11 then \"Autunno\"\n    else \"Inverno\"\n}\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r._field == \"value\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      dayOfWeek: date.weekDay(t: r._time),\n      ora: date.hour(t: r._time),\n      stagione: calcStagione(mese: date.month(t: r._time))\n  }))\n\n  |> filter(fn: (r) => r.stagione == \"Autunno\")\n  |> map(fn: (r) => ({ r with dayOfWeek: if r.dayOfWeek == 0 then 7 else r.dayOfWeek }))\n  |> group(columns: [\"dayOfWeek\", \"ora\"]) \n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\n  |> sort(columns: [\"ora\"])\n  |> group(columns: [\"dayOfWeek\"]) "
    }
   ]
  },
  {
   "title": "Profilo giorno medio: INVERNO",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\ncalcStagione = (mese) => {\n    return if mese >= 3 and mese <= 5 then \"Primavera\"\n    else if mese >= 6 and mese <= 8 then \"Estate\"\n    else if mese >= 9 and mese <= 11 then \"Autunno\"\n    else \"Inverno\"\n}\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r._field == \"value\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      dayOfWeek: date.weekDay(t: r._time),\n      ora: date.hour(t: r._time),\n      stagione: calcStagione(mese: date.month(t: r._time))\n  }))\n\n  |> filter(fn: (r) => r.stagione == \"Inverno\")\n  |> map(fn: (r) => ({ r with dayOfWeek: if r.dayOfWeek == 0 then 7 else r.dayOfWeek }))\n  |> group(columns: [\"dayOfWeek\", \"ora\"]) \n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\n  |> sort(columns: [\"ora\"])\n  |> group(columns: [\"dayOfWeek\"]) "
    }
   ]
  },
  {
   "title": "Confronto profilo inverno vs estate",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\ncalcStagione = (mese) => {\n    return if mese >= 3 and mese <= 5 then \"Primavera\"\n    else if mese >= 6 and mese <= 8 then \"Estate\"\n    else if mese >= 9 and mese <= 11 then \"Autunno\"\n    else \"Inverno\"\n}\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r._field == \"value\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      dayOfWeek: date.weekDay(t: r._time),\n      ora: date.hour(t: r._time),\n      stagione: calcStagione(mese: date.month(t: r._time))\n  }))\n\n  |> filter(fn: (r) => r.stagione == \"Inverno\" or r.stagione ==\"Estate\")\n  |> map(fn: (r) => ({ r with dayOfWeek: if r.dayOfWeek == 0 then 7 else r.dayOfWeek }))\n  |> group(columns: [\"stagione\", \"ora\"]) \n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\n  |> group(columns: [\"stagione\"]) \n  |> sort(columns: [\"ora\"])"
    }
   ]
  },
  { "title": "Sintesi annuale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Curva di richiesta del carico elettrico",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => \n      r._measurement == \"kWh\" and \n      r._field == \"value\" and\n      r[\"type_measure\"] == \"energia\" and\n      r.device_id == ${deviceId}\n  )\n  |> group(columns: [\"device_id\"]) \n  |> aggregateWindow(every: 1h, fn: sum, createEmpty: false)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: if exists r._value then float(v: r._value) else 0.0,\n  }))"
    }
   ]
  },
  {
   "title": "Consumo in fasce",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\ncalcStagione = (mese) => {\n    return if mese >= 3 and mese <= 5 then \"Primavera\"\n    else if mese >= 6 and mese <= 8 then \"Estate\"\n    else if mese >= 9 and mese <= 11 then \"Autunno\"\n    else \"Inverno\"\n}\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r.fascia != \"0\" and r.fascia != \"\" and r._field == \"value\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> group(columns: [\"fascia\"]) \n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Sintesi mensile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Consumo mensile in fasce",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "query": "import \"date\"\nimport \"timezone\"\n\n\nfrom(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"kWh\" and r._field == \"value\" and r.fascia != \"0\" and r.fascia != \"\" and  r[\"type_measure\"] == \"energia\" and r.device_id == ${deviceId})\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: r._value,\n      fascia: r.fascia,\n      mese: date.month(t: r._time)\n  }))\n\n  |> group(columns: [\"mese\", \"fascia\"])\n  |> aggregateWindow(every: 1y, fn: mean, createEmpty: false)\n  |> group(columns: [\"mese\"])"
    }
   ]
  }
 ]
}